type Board {
  id: ID!
  title: String!
  version: Int!
  widgets: [WidgetPayload!]!
}

type Query {
  board(id: ID!): Board
  boards: [Board!]!
}

type Subscription {
  boardUpdated(boardId: ID!): Board!
}

type WidgetPayload {
  id: ID!
  type: String!
  x: Float!
  y: Float!
  width: Float!
  height: Float!
  configJson: String!
}

input WidgetInput {
  id: ID!
  type: String!
  x: Float!
  y: Float!
  width: Float!
  height: Float!
  configJson: String!
}

type Mutation {
  createBoard(title: String!): Board!
  saveBoard(boardId: ID!, version: Int!, widgets: [WidgetInput!]!): Board!
}
