// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Board struct {
	ID      string           `json:"id"`
	Title   string           `json:"title"`
	Version int              `json:"version"`
	Widgets []*WidgetPayload `json:"widgets"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type WidgetInput struct {
	ID         string  `json:"id"`
	Type       string  `json:"type"`
	X          float64 `json:"x"`
	Y          float64 `json:"y"`
	Width      float64 `json:"width"`
	Height     float64 `json:"height"`
	ConfigJSON string  `json:"configJson"`
}

type WidgetPayload struct {
	ID         string  `json:"id"`
	Type       string  `json:"type"`
	X          float64 `json:"x"`
	Y          float64 `json:"y"`
	Width      float64 `json:"width"`
	Height     float64 `json:"height"`
	ConfigJSON string  `json:"configJson"`
}
